package com.grocery.enums;

public enum Category {
	FRUITS_AND_VEGETABLES,
	DAIRY_AND_EGGS,
	BAKERY,
	BEVERAGES,
	SNACKS,
	MEAT_AND_SEAFOOD,
	GRAINS_AND_PULSES,
	FROZEN_FOODS,
	HOUSEHOLD_ESSENTIALS,
	PERSONAL_CARE,
	OTHERS
}
